[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/lmao-model"
edition = "2018"
homepage = "https://github.com/lmao-rs/lmao"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "lmao"]
license = "ISC"
name = "lmao-model"
publish = false
readme = "README.md"
repository = "https://github.com/lmao-rs/lmao.git"
version = "0.1.0"

[dependencies]
bitflags = "1"
chrono = { features = ["serde"], optional = true, version = "0.4" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
serde_repr = "0.1"

[features]
default = ["chrono", "chrono/serde"]
