[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/dawn-model"
edition = "2018"
homepage = "https://github.com/dawn-rs/dawn"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-model"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
bitflags = "1"
serde = { features = ["derive"], optional = true, version = "1" }
serde-mappable-seq = { optional = true, version = "0.1" }
serde_repr = { optional = true, version = "0.1" }
serde-value = { optional = true, version = "0.6" }

[dev-dependencies]
serde_test = "1"

[features]
default = ["serde-support"]
serde-support = ["serde", "serde-mappable-seq", "serde_repr", "serde-value"]
