[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
edition = "2018"
name = "twilight-gateway-example-shard"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../.." }
futures = "0.3"
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
