[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
edition = "2018"
name = "dawn-gateway-example-shard"
version = "0.1.0"

[dependencies]
dawn-gateway = { path = "../.." }
futures-preview = "0.3.0-alpha.19"
pretty_env_logger = "0.3"
tokio = "0.2.0-alpha.6"
