[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/dawn-http"
edition = "2018"
homepage = "https://github.com/dawn-rs/dawn"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-http"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
futures-channel-preview = "0.3.0-alpha.18"
futures-core-preview = "0.3.0-alpha.18"
futures-util-preview = "0.3.0-alpha.18"
futures-timer = "0.4"
http = "0.1"
dawn-model = { path = "../model" }
log = "0.4"
reqwest = { default-features = false, features = ["rustls-tls"], git = "https://github.com/seanmonstar/reqwest", rev = "f4100e4148dad8176608eb7bd2a530e719e61cc8" }
serde = "1"
serde_json = "1"
snafu = "0.5"
tokio = "0.2.0-alpha.4"
url = "2"
