[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
edition = "2018"
name = "twilight-gateway-example-cluster"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../.." }
futures = "0.3"
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
