[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
edition = "2018"
name = "twilight-http-example-get-message"
publish = false
version = "0.0.1"

[dependencies]
twilight-http = { path = "../.." }
twilight-model = { path = "../../../model" }
futures = "0.3"
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
