name: CI

env:
  minrust: 1.48.0

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    #branches:
    #    - staging
    #    - trying

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests

  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
          key: ${{ runner.os }}-docs-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs -D broken_intra_doc_links
        run: |
          cargo doc --workspace --no-deps
          cargo doc -p twilight-util --no-deps --all-features

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  sync-readme:
    name: Sync readme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install cargo-sync-readme
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-sync-readme
          version: latest

      - name: Run in command-parser
        run: cd command-parser && cargo sync-readme --check
      - name: Run in gateway
        run: cd gateway && cargo sync-readme --check
      - name: Run in http
        run: cd http && cargo sync-readme --check
      - name: Run in lavalink
        run: cd lavalink && cargo sync-readme --check
      - name: Run in model
        run: cd model && cargo sync-readme --check
      - name: Run in standby
        run: cd standby && cargo sync-readme --check
      - name: Run in twilight
        run: cd twilight && cargo sync-readme --check
      - name: Run in embed-builder
        run: cd embed-builder && cargo sync-readme --check
      - name: Run in mention
        run: cd mention && cargo sync-readme --check
      - name: Run in util
        run: cd util && cargo sync-readme --check

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test
        run: cargo test

  test-features:
    name: Test ${{ matrix.package }} feat. ${{ matrix.features }}
    needs: [test]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - http
          - gateway
          - lavalink
        features:
          - native
          - rustls
          - simd-json

        include:
          - package: http
            features: simd-json
            additional: --features rustls
            rustflags: "-C target-cpu=native"
          - package: gateway
            features: rustls
            additional: --features stock-zlib
          - package: gateway
            features: native
            additional: --features stock-zlib
          - package: gateway
            features: simd-json
            additional: --features rustls,stock-zlib
            rustflags: "-C target-cpu=native"
          - package: lavalink
            additional: --features http-support

          - package: util
            features: full

        exclude:
          - package: lavalink
            features: simd-json

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Test ${{ matrix.package }} feat. ${{ matrix.features }}
        working-directory: ${{ matrix.package }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: |
          cargo test --no-default-features --features ${{ matrix.features }} ${{ matrix.additional }}

  test-msrv:
    name: Test MSRV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain (${{ env.minrust }})
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.minrust }}
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-msrv-${{ steps.tc.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo check --examples --tests --all-features
        env:
          RUSTFLAGS: "-C target-cpu=native"

  done:
    name: Done
    needs: [clippy, docs, format, sync-readme, test, test-features, test-msrv]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done
