[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/twilight"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
version = "0.1.0"

[dependencies]
twilight-cache = { optional = true, path = "../cache/base" }
twilight-command-parser = { optional = true, path = "../command-parser" }
twilight-gateway = { optional = true, path = "../gateway" }
twilight-http = { optional = true, path = "../http" }
twilight-model = { optional = true, path = "../model" }
twilight-builders = { optional = true, path = "../builders" }

[dev-dependencies]
futures = "0.3"
tokio = "0.2"

[features]
default = ["cache", "command-parser", "gateway", "http", "model", "builders"]

cache = ["twilight-cache"]
command-parser = ["twilight-command-parser"]
gateway = ["twilight-gateway"]
http = ["twilight-http"]
model = ["twilight-model"]
builders = ["twilight-builders"]

metrics = ["gataway-metrics"]
gataway-metrics = ["gateway", "twilight-gateway/metrics"]
